export const KNOWN_ENTITIES: { canonical: string; aliases: string[]; ecosystem: string }[] = [
  { canonical: 'next.js',      aliases: ['nextjs', 'next.js', 'next js'],         ecosystem: 'node' },
  { canonical: 'react',        aliases: ['react.js', 'reactjs'],                  ecosystem: 'node' },
  { canonical: 'langchain',    aliases: ['lc', 'langchain-py', 'langchain.js'],   ecosystem: 'python' },
  { canonical: 'openai',       aliases: ['openai-python', 'gpt-4', 'gpt-5'],      ecosystem: 'python' },
  { canonical: 'anthropic',    aliases: ['claude', 'anthropic-sdk'],              ecosystem: 'python' },
  { canonical: 'fastapi',      aliases: [],                                       ecosystem: 'python' },
  { canonical: 'transformers', aliases: ['hf-transformers'],                      ecosystem: 'python' },
  { canonical: 'vllm',         aliases: [],                                       ecosystem: 'python' },
  { canonical: 'llama.cpp',    aliases: ['llama-cpp', 'llamacpp'],                ecosystem: 'cpp' },
  { canonical: 'ollama',       aliases: [],                                       ecosystem: 'tool' },
  { canonical: 'kubernetes',   aliases: ['k8s'],                                  ecosystem: 'devops' },
  { canonical: 'docker',       aliases: [],                                       ecosystem: 'devops' },
  { canonical: 'terraform',    aliases: [],                                       ecosystem: 'devops' },
  { canonical: 'postgres',     aliases: ['postgresql', 'pg'],                     ecosystem: 'data' },
  { canonical: 'redis',        aliases: [],                                       ecosystem: 'data' },
  { canonical: 'pgvector',     aliases: [],                                       ecosystem: 'data' },
  { canonical: 'qdrant',       aliases: [],                                       ecosystem: 'data' },
  { canonical: 'aws',          aliases: ['amazon web services'],                  ecosystem: 'cloud' },
  { canonical: 'gcp',          aliases: ['google cloud'],                         ecosystem: 'cloud' },
  { canonical: 'cloudflare',   aliases: [],                                       ecosystem: 'cloud' },
  { canonical: 'vercel',       aliases: [],                                       ecosystem: 'cloud' },
  { canonical: 'typescript',   aliases: ['ts'],                                   ecosystem: 'lang' },
  { canonical: 'python',       aliases: ['cpython'],                              ecosystem: 'lang' },
  { canonical: 'rust',         aliases: [],                                       ecosystem: 'lang' },
  { canonical: 'golang',       aliases: ['go-lang'],                              ecosystem: 'lang' },
  { canonical: 'node.js',      aliases: ['nodejs', 'node'],                       ecosystem: 'lang' },
  { canonical: 'bun',          aliases: ['bun.sh'],                               ecosystem: 'lang' },
  { canonical: 'deno',         aliases: [],                                       ecosystem: 'lang' },
  { canonical: 'prisma',       aliases: [],                                       ecosystem: 'data' },
  { canonical: 'supabase',     aliases: [],                                       ecosystem: 'backend' },
];
